version: '3.9'
services:
  server:
    build: .
    container_name: socket-server
    command: ["java", "-cp", "target/classes", "br.com.fiap.cp5_socket.Server"]
    ports:
      - "5000:5000"
    networks:
      - socket-net

  client:
    build: .
    container_name: socket-client
    command: ["java", "-cp", "target/classes", "br.com.fiap.cp5_socket.Client"]
    depends_on:
      - server
    networks:
      - socket-net

networks:
  socket-net:
    driver: bridge
